
(function(){
  const standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  const prefix=standalone?'shambhuAppSettings':'shambhuWebsiteSettings';
  const defaults={font:'normal',fontStyle:'Arial,Helvetica,sans-serif',fontSize:14,fontColor:'#17332b',view:'auto',theme:'light',lang:'en',pin:true,bio:false,autoLock:300000,refresh:30000};
  function read(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(prefix)||'{}'))}catch(e){return {...defaults}}}
  function write(x){localStorage.setItem(prefix,JSON.stringify(x))}
  function themeApply(v){document.documentElement.classList.remove('theme-dark','theme-light');let dark=v==='dark'||(v==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('theme-dark',dark);document.documentElement.classList.toggle('theme-light',!dark)}
  function fontApply(v){document.body.classList.remove('font-small','font-normal','font-large');document.body.classList.add('font-'+v);const x=read();document.documentElement.style.setProperty('--user-font',x.fontStyle||'Arial,Helvetica,sans-serif');document.documentElement.style.setProperty('--user-size',(Number(x.fontSize)||14)+'px');document.documentElement.style.setProperty('--user-color',x.fontColor||'#17332b');document.body.style.fontFamily='var(--user-font)';document.body.style.fontSize='var(--user-size)';document.body.style.color='var(--user-color)';if(x.view==='mobile')document.body.classList.add('settings-mobile');else if(x.view==='desktop')document.body.classList.add('settings-desktop');}
  function apply(){const x=read();themeApply(x.theme);fontApply(x.font);window.SHAMBHU_REFRESH_MS=Number(x.refresh)||0;if(x.refresh!==undefined)window.dispatchEvent(new CustomEvent('shambhu-refresh-setting',{detail:x.refresh}));}
  window.openSettings=function(){const x=read();$('settingsOverlay').classList.add('show');$('settingsOverlay').setAttribute('aria-hidden','false');$('websiteTheme').value=standalone?readWebsiteTheme():x.theme;$('appTheme').value=readAppTheme();$('pinToggle').checked=x.pin;$('bioToggle').checked=x.bio;$('autoLock').value=String(x.autoLock);$('refreshRate').value=String([15000,30000,60000].includes(Number(x.refresh))?x.refresh:30000);$('fontStyle').value=x.fontStyle||defaults.fontStyle;$('fontSizeNum').value=x.fontSize||14;$('fontColor').value=x.fontColor||defaults.fontColor;document.querySelectorAll('#viewSeg button').forEach(b=>b.classList.toggle('active',b.dataset.view===(x.view||'auto')));document.querySelectorAll('#fontSeg button').forEach(b=>b.classList.toggle('active',b.dataset.font===x.font));document.querySelectorAll('#langSeg button').forEach(b=>b.classList.toggle('active',b.dataset.lang===x.lang));$('bioStatus').textContent=x.bio?'Biometric enabled for this device.':'Biometric not set up.';$('refreshStatus').textContent='Auto refresh: '+(x.refresh?((x.refresh/1000)+' seconds'):'Off');};
  window.closeSettings=function(){$('settingsOverlay').classList.remove('show');$('settingsOverlay').setAttribute('aria-hidden','true')};
  function readWebsiteTheme(){try{return JSON.parse(localStorage.getItem('shambhuWebsiteSettings')||'{}').theme||'light'}catch(e){return'light'}}
  function readAppTheme(){try{return JSON.parse(localStorage.getItem('shambhuAppSettings')||'{}').theme||'light'}catch(e){return'light'}}
  window.saveSettings=function(){const x=read();x.font=document.querySelector('#fontSeg .active')?.dataset.font||'normal';x.fontStyle=$('fontStyle').value;x.fontSize=Math.max(10,Math.min(30,Number($('fontSizeNum').value)||14));x.fontColor=$('fontColor').value;x.view=document.querySelector('#viewSeg .active')?.dataset.view||'auto';x.lang=document.querySelector('#langSeg .active')?.dataset.lang||'en';x.pin=$('pinToggle').checked;x.bio=$('bioToggle').checked;x.autoLock=Number($('autoLock').value);x.refresh=Number($('refreshRate').value);x.theme=standalone?$('appTheme').value:$('websiteTheme').value;write(x);localStorage.setItem('shambhuWebsiteSettings',JSON.stringify({...JSON.parse(localStorage.getItem('shambhuWebsiteSettings')||'{}'),theme:$('websiteTheme').value,lang:standalone?(JSON.parse(localStorage.getItem('shambhuWebsiteSettings')||'{}').lang||'en'):x.lang}));localStorage.setItem('shambhuAppSettings',JSON.stringify({...JSON.parse(localStorage.getItem('shambhuAppSettings')||'{}'),theme:$('appTheme').value,lang:standalone?x.lang:(JSON.parse(localStorage.getItem('shambhuAppSettings')||'{}').lang||'en')}));apply();window.SHAMBHU_AUTOLOCK_MS=x.autoLock;closeSettings();alert('Settings saved. Website/App settings are stored separately.')};
  window.resetSettings=function(){write({...defaults});apply();openSettings()};
  document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('#viewSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#viewSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('#fontSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#fontSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('#langSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#langSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('settingsOverlay').addEventListener('click',e=>{if(e.target.id==='settingsOverlay')closeSettings()});apply();});
  window.setupDeviceBiometric=async function(){if(!window.PublicKeyCredential||!navigator.credentials){$('bioStatus').textContent='This browser/device does not support device biometric WebAuthn.';return}try{const challenge=crypto.getRandomValues(new Uint8Array(32));const cred=await navigator.credentials.create({publicKey:{challenge,rp:{name:'Shambhu Shed QC'},user:{id:crypto.getRandomValues(new Uint8Array(16)),name:'shambhu-shed-user',displayName:'Shambhu Shed'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required'},timeout:60000}});if(cred){localStorage.setItem('shambhuBiometricCredential','1');$('bioToggle').checked=true;$('bioStatus').textContent='Device biometric registered. Fingerprint/face/PIN prompt depends on your phone security settings.'}}catch(e){$('bioStatus').textContent='Biometric setup cancelled or unavailable on this device.'}};
  window.tryDeviceBiometric=async function(){if(localStorage.getItem('shambhuBiometricCredential')!=='1')return false;try{const challenge=crypto.getRandomValues(new Uint8Array(32));const a=await navigator.credentials.get({publicKey:{challenge,timeout:60000,userVerification:'required',allowCredentials:[]}});return !!a}catch(e){return false}};
  let refreshTimer;function startRefresh(ms){clearInterval(refreshTimer);if(ms>0)refreshTimer=setInterval(()=>{if(typeof load==='function'&&!document.hidden)load()},ms)}
  window.addEventListener('shambhu-refresh-setting',e=>startRefresh(Number(e.detail)||0));window.addEventListener('load',()=>{apply();startRefresh(read().refresh)});
})();
